logging:
  level:
    root: ERROR

server:
  address: 127.0.0.1
  port: 0
  display-name: Integration Provisioning Tool
  context-path: /provisioning
  tomcat:
    basedir: /data/symphony/ib/tomcat

spring:
  profiles:
    active: jira, github, salesforce, universal, trello, zapier